apiVersion: v2
name: zea
description: Zea backend - Argo CD proxy extension for building and deploying from one screen
type: application
version: 0.1.3
appVersion: "0.1.3"
home: https://github.com/harchschoolboy/argocd-zea
sources:
  - https://github.com/harchschoolboy/argocd-zea
keywords:
  - argocd
  - argo-cd-extension
  - github-actions
